export default {
  offer: "Oferta",
  road_header: "Transport drogowy",
  road_p:
    "Sprawna relokacja towarów stanowi obecnie podstawę funkcjonowania każdej gospodarki i firmy. Dzięki możliwości szybkiego i bezpiecznego transportowania ładunków możliwe są procesy produkcyjne, a konsumenci mają dostęp do szerokiej gamy wyrobów. Wśród trzech standardowych gałęzi transportu – morskiego, lotniczego i drogowego – każdy ma swoją specyfikę i jest wykorzystywany w określonym obszarze usług spedycyjnych. Towarowy transport drogowy ma wiele zalet, wśród których najważniejsze to: łatwa dostępność środków transportu oraz ich duża różnorodność (samochody chłodnie, cysterny, wywrotki, pojazdy specjalne do przewozu drutu czy papieru w kręgach i wiele innych), rozbudowana sieć dróg, które pozwalają dotrzeć jednym pojazdem do najdalszego zakątka kontynentu, bez potrzeby kosztownych przestojów czy przeładunku, relatywnie niskie koszty transportu (bez kosztów magazynowania, przeładunku, opłat tranzytowych, czarterowych i wielu innych – koszty uzależnione od odległości), możliwość dostawy door-to-door, dzięki której zlecenie jest realizowane szybciej, taniej i bez strat delikatnych materiałów. Transcomlogistics jest firmą spedycyjną, dla której nie istnieją granice i lokalizacje niedostępne. Planujemy i organizujemy przewozy zarówno na krótkich dystansach, jak i w odległe zakątki świata. Naszą specjalnością jest zarówno krajowy transport drogowy, w ramach którego ekspediujemy przesyłki kontenerowe, drobnicowe, ponadgabarytowe i specjalne. Organizujemy również międzynarodowy transport drogowy, zarówno do państw Unii Europejskiej jak i poza nią. Towarowe przewozy drogowe planujemy też za potrzeby spedycji łączonej ze spedycją morską lub lotniczą.",
  naval_header: "Transport morksi",
  naval_p:
    "Spedycja to szereg procesów, których celem jest transport towarów zgodnie z wymaganiami klienta. W przesyłaniu ładunków wykorzystuje się różne środki transportowe. Bezpieczną i ekonomiczną formą transportu dóbr jest transport morski. CZYM JEST TRANSPORT MORSKI? Transport morski to jedna z usług spedycyjnych, która do przesyłania różnego rodzaju ładunków wykorzystuje statki morskie. Fracht morski wykorzystywany jest przede wszystkim dla towarów, które nie wymagają ekspresowego transportu. Czas realizacji w przypadku frachtu morskiego zdecydowanie się wydłuża, dlatego nie może on być priorytetem. Spedycja morska perfekcyjnie sprawdza się w przesyłaniu ładunków o dużych gabarytach. Regularne linie żeglugowe wykorzystywane są najczęściej w przewożeniu ładunków, do czego firmy spedycyjne wykorzystują dostępne serwisy armatorów morskich. Najważniejsze rodzaje spedycji morskiej, to transport pełnokontenerowy (FCL – Full Container Load) oraz transport drobnicowy (LCL – Less Container Load). CZY WYSYŁKA ŁADUNKÓW DROGĄ MORSKĄ JEST OPŁACALNA? Transport kontenerowy to zdecydowanie najbardziej ekonomiczny rodzaj frachtu. Drogą morską przesyłać można ładunki o każdym gabarycie oraz w dowolnej ilości. Ta forma transportu towarów jest niezwykle bezpieczna. Niskie koszty sprawiają, że wciąż duża liczba klientów korzysta ze spedycji morskiej. Warto jednak pamiętać, że atrakcyjna cena, w porównaniu do transportu lotniczego, wiąże się z długim terminem realizacji. Dobrze jest zatem odpowiednio wcześnie zaplanować nadanie towaru.",
  air_header: "Transprort lotniczy",
  air_p:
    "Goods can be transported in many ways. The task of companies providing forwarding services is to provide comprehensive transport services tailored to the needs of customers. The form of transport of goods that guarantees safety and fast delivery time over long distances is air transport and logistics of shipments sent by air. AIR FREIGHT – WHAT DOES IT ALLOW? Each form of forwarding meets different customer needs. By choosing air transport, the customer receives a guarantee of fast and reliable shipment of goods. The use of the air route in forwarding is perfect for shipping highly processed and valuable goods over long distances. The use of air freight allows you to ship almost any type of goods and goods. Cargo air transport allows you to transport heavy elements and goods of non-standard dimensions, large dimensions and weight on board the aircraft. By air, goods with a short shelf life, including perishable ones, are transported effectively and in an express time. AIR TRANSPORT - ADVANTAGES An extremely important advantage of air transport is the delivery time. Currently, the air route is a variant that allows for very fast delivery of goods to selected destinations, as the vast majority of airports in the world enable forwarding activities. This form of transport also ensures safety. Using air freight transport, it is possible to import and export all goods, even dangerous goods, in the country and around the world. Both business and individual customers can use air freight.",
};
