import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Hero from "../views/hero/Hero";
import Nav from "../views/Nav/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <main>
        <div className={styles.main_top}>
          <Nav />
          <Hero />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
