import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import About from "../views/about/About";
import Add from "../views/add/Add";
import Contact from "../views/contact/Contact";
import Email from "../views/email/Email";
import Footer from "../views/footer/Footer";
import Hero from "../views/hero/Hero";
import Memorials from "../views/memorials/Memorials";
import Nav from "../views/Nav/Nav";
import Offer from "../views/offer/Offer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <main>
        <div className={styles.main_top}>
          <Nav />
          <Hero />
        </div>
        <About />
        <Offer />
        <Add />
        <Memorials />
        <Contact />
        <Email />
        <Footer />
      </main>

      <footer></footer>
    </div>
  );
}
