import Head from "next/head";
import Image from "next/image";
import Router from "next/router";
import { useEffect } from "react";
import styles from "../styles/Home.module.scss";
import About from "../src/views/about/About";
import Add from "../src/views/add/Add";
import Contact from "../src/views/contact/Contact";
import Email from "../src/views/email/Email";
import Footer from "../src/views/footer/Footer";
import Hero from "../src/views/hero/Hero";
import Memorials from "../src/views/memorials/Memorials";
import Nav from "../src/views/nav/Nav";
import Offer from "../src/views/offer/Offer";
import NotificationProvider from "../store/notification-context";

export default function Home() {
  useEffect(() => {
    const locale = "pl";
    Router.push("/", "/", { locale });
  }, []);
  return (
    // <NotificationProvider>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>

      <main>
        <div className={styles.main_top} name="top">
          <Nav />
          <Hero />
        </div>
        <About />
        <Offer />
        <Add />
        <Memorials />
        <Contact />
        <Email />
        <Footer />
      </main>
    </div>
    // </NotificationProvider>
  );
}
